### PR TITLE
Remove Jenkinsfile

### PR DESCRIPTION
**Pull request by darxriggs**
The project uses Travis. Therefore the `Jenkinsfile` is not required anymore.

### CODE REVIEW

**Comment by slonopotamus** [comment]
Actually, git-lfs-java doesn't use Jenkins for CI for a long time. @bozaro has a personal Jenkins machine, but since he isn't actively working on git-lfs-java and I do not have access to that machine, it made sense to switch to some public CI service.

**Comment by darxriggs** [comment]
The `Jenkinsfile` then should be remove - right?

**Comment by slonopotamus** [comment]
Yep

**Comment by darxriggs** [comment]
I updated the commit and pull request accordingly.

**Pull request merged**
