### PR TITLE
Upgrade to Gradle 6.0.1

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by slonopotamus** [comment]
Thanks!

**Comment by slonopotamus** [comment]
Something broke: https://travis-ci.org/bozaro/git-lfs-java/jobs/630895123

**Comment by darxriggs** [comment]
I will have a look.

**Comment by slonopotamus** [comment]
So, we're hitting gradle/gradle#11387. Possibly the easiest solution is to revert Gradle bump and just wait until that issue gets fixed.

**Comment by darxriggs** [comment]
You found the better issue. I found other discussions that said disabling the Gradle Module Metadata would resolve the issue but that would only be a workaround. I was in the process of preparing something like:

    tasks.withType<GenerateModuleMetadata> {
        enabled = !project.version.toString().endsWith("-SNAPSHOT")
    }

But now seeing the issue you found, the better alternative is to revert the Gradle upgrade.

**Comment by slonopotamus** [comment]
> You will do this on your own - right?

Yeah, don't worry.

**Pull request merged**
